services:
  - type: web
    name: glamglow-whatsapp-api
    env: node
    plan: free
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-131.0.6778.204/chrome-linux64/chrome
